### ISSUE TITLE
Automazione deployment da CI

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-infrastructure#131]
In ambiente di CI/CD dovrebbe essere possibile aggiornare i deployment dell'ambiente staging in maniera automatizzata.

Ipotesi:
- ingress controller con [mutua autenticazione](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#client-certificate-authentication) su ambiente staging
- pod con ServiceAccount abilitato alla modifica dei deployment nel ns

**Comment by giafar** [comment]
Risolta con https://github.com/AgID/wai-infrastructure/pull/203/commits/ffca92129ccf0d5790b8726cbd3afbbb160babc2

**Comment by pdavide** [comment]
Closed in #229.
