### ISSUE TITLE
Errore su sentinel (down)

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-infrastructure#146]
Riporto messaggio su slack di @giafar 
> il sentinel ha nelle sue configurazioni sentinel known-sentinel ipa-redisearch-master 10.233.72.19 26379 ce7bd14ac072491f5a6275867b81a5d0d5d3f6c9  dovuto probabilmente alla riallocazione dell’ip 10.233.72.19  che prima era di un sentinel e poi è passato ad un portal (lo stato attuale infatti è s_down,sentinel) … cerco di capire come fargli fare il drop del sentinel.

**Comment by giafar** [comment]
[Redis docs](https://redis.io/topics/sentinel) 
*SENTINEL reset <pattern> This command will reset all the masters with matching name. The pattern argument is a glob-style pattern. The reset process clears any previous state in a master (including a failover in progress), and removes every replica and sentinel already discovered and associated with the master.*

Per eseguire il drop del sentinel è necessario collegarsi a tutti i sentinel e richiedere il reset del master, ad esempio:
```bash
kubectl exec -it -n wai-stag ipa-redisearch-slave-1 -c sentinel -- redis-cli -p 26379 sentinel reset ipa-redisearch-master
```

Potremmo richiedere alla conduzione di verificare i log di ES alla ricerca di errori Wave che suggeriscono evidenziano il problema.

**Comment by pdavide** [comment]
Superseded by #183.
