### ISSUE TITLE
Configmap con dump sql per reset matomo

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-infrastructure#187]
Come si discuteva in https://github.com/AgID/wai-portal/issues/387#issuecomment-590861105, si dovrebbe creare una configmap che riporti il dump sql di matomo core (così come nel template jinja caricato qui nel repo) e poi, nello script contenuto nell configmap `matomo-initc-config`, si dovrebbe creare un nuovo dump completo che includa il core e tutti gli script premium presenti nel volume `matomo-extra-content`.
Il file così creato dovrebbe essere messo a disposizione di un nuovo cronjob che avrà lo scopo di resettare l'ambiente `public-playground` periodicamente mediante l'uso del comando reso disponibile dal plugin https://github.com/AgID/wai-matomo-plugin-ResetDatabase.

**Comment by giafar** [comment]
Una soluzione potrebbe essere quella di creare i file per il reset del database a runtime ovvero ricompilare quanto presente nei repo e nei plugin in base alla effettiva situazione del sistema.
In pratica quello che potremmo fare è, a partire dalla versione di matomo che potrebbe essere inserito in una configurazione:

- Scaricare il [template del dump del database](https://raw.githubusercontent.com/AgID/wai-infrastructure/develop/playbooks/templates/mariadb/matomo_3_13_5.sql.j2);
- Tramite una configmap gestire le variabili necessarie alla compilazione del template, magare tramite configmap dedicata generata da ansible nel momento del deployment della soliuzione (ovviamente non ora ma prevediamo configmap nel playbook);
- Eseguire jinja2 per compilare il template ottenendo il file originario;
- Aprire i plugin estraendo i file sql contenuti al loro interno;
- Eseguire il comando [https://github.com/AgID/wai-matomo-plugin-ResetDatabase]( https://github.com/AgID/wai-matomo-plugin-ResetDatabase);

Il medesimo approccio potrebbe essere eseguito per eseguire il reset del database di portal.

Entrambe le procedure potrebbero essere inserite all'interno di un job di kuberntes che contiene un POD con due container, uno per matomo e l'altro per portal.

@pdavide Ti torna tutto ?

**Comment by pdavide** [comment]
@giafar si tutto come ci eravamo anticipati in call.

Per il portale la procedura sarà più semplice perché non ci serve il dump del db, ma solo lanciare il comando `bin/app/artisan app:reset-environment` che si occupa di tutto. Ho rimosso lo scheduling interno del portale visto che faremo tutto da K8S (https://github.com/AgID/wai-portal/commit/8cb0aa8fb0f5dd3a00b40afb1207d98e932cda72).
In aggiunta, per il portale, come scrivevo [nel commento alla issue di riferimento](https://github.com/AgID/wai-portal/issues/387#issuecomment-588205481), è necessario risolvere anche la #186.

**Comment by pdavide** [comment]
Fixed in #198.
