### ISSUE TITLE
Egress mail server rule

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-infrastructure#189]
https://github.com/AgID/wai-infrastructure/blob/357d277b9002d98ddb71fdba332d3436caa1fbd8/playbooks/templates/k8s/namespace/00_network-policy.yml.j2#L68
Change to configurable value.

**Comment by giafar** [comment]
Risolta con https://github.com/AgID/wai-infrastructure/pull/203/commits/af22b5821f19cd7bd7a8923d54b9a09ce6dcaadc
