### ISSUE TITLE
Gestione degli aggiornamenti (rolling update) dei container in K8S

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-infrastructure#35]
Tutti i container dovrebbero essere aggiornabili (in modalità _rolling update_).

Gli ambienti di produzione e public-playground dovrebbero seguire gli aggiornamenti secondo le nuove release stabili delle immagini dei container.

L'ambiente staging dovrebbe seguire gli aggiornamenti di tutte le release (anche in versione non stabile) delle immagini dei container.

**Comment by giafar** [comment]
Aggiunta possibilità di eseguire il patch dei pod tramite https://github.com/AgID/wai-infrastructure/pull/203/commits/ffca92129ccf0d5790b8726cbd3afbbb160babc2

**Comment by pdavide** [comment]
Closed in #229.
